language: python

python:
  - 2.7
  - 3.6
  - 3.7

os:
  - linux
  - osx

env:
  - TARGET_TSLEARN_VERSION="0.2.4"

install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == 2.* ]];
  then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION Cython numpy>=1.14 scipy tensorflow keras
  scikit-learn numba joblib>=0.12 pandas
- conda install -c conda-forge conda-press
- source activate test-environment
- pip install cesium pytest

script:
- export TOXENV="py${TRAVIS_PYTHON_VERSION/./}"
- conda press --subdir ${TRAVIS_OS_NAME}-64 --skip-python --fatten tslearn=${TARGET_TSLEARN_VERSION}=${TOXENV}* -o tslearn-${TARGET_TSLEARN_VERSION}-${TOXENV}-${TRAVIS_OS_NAME}.whl;
- pip install tslearn-${TARGET_TSLEARN_VERSION}-${TOXENV}-${TRAVIS_OS_NAME}.whl;
- pytest --pyargs tslearn

#after_success:
#- # TODO

notifications:
  email: false
